spring:
  application:
    name: flowermarket
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=flowermarket;encrypt=true;trustServerCertificate=true
    username: flowermarket
    password: flowermarket
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

secrets:
  jwt_secret: ${JWT_SECRET}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui